"""empty message

Revision ID: 95ac11e140fd
Revises: ee86092e3711
Create Date: 2021-02-26 22:38:33.385676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95ac11e140fd'
down_revision = 'ee86092e3711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('climate', sa.String(length=80), nullable=False))
    op.add_column('planets', sa.Column('diameter', sa.Integer(), nullable=False))
    op.add_column('planets', sa.Column('gravity', sa.String(length=80), nullable=False))
    op.add_column('planets', sa.Column('name', sa.String(length=80), nullable=False))
    op.add_column('planets', sa.Column('orbital_period', sa.Integer(), nullable=False))
    op.add_column('planets', sa.Column('population', sa.Integer(), nullable=False))
    op.add_column('planets', sa.Column('rotation_period', sa.Integer(), nullable=False))
    op.add_column('planets', sa.Column('surface_water', sa.Integer(), nullable=False))
    op.add_column('planets', sa.Column('terrain', sa.String(length=80), nullable=False))
    op.add_column('planets', sa.Column('url', sa.String(length=80), nullable=False))
    op.drop_column('planets', 'done')
    op.drop_column('planets', 'label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('label', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('planets', sa.Column('done', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('planets', 'url')
    op.drop_column('planets', 'terrain')
    op.drop_column('planets', 'surface_water')
    op.drop_column('planets', 'rotation_period')
    op.drop_column('planets', 'population')
    op.drop_column('planets', 'orbital_period')
    op.drop_column('planets', 'name')
    op.drop_column('planets', 'gravity')
    op.drop_column('planets', 'diameter')
    op.drop_column('planets', 'climate')
    # ### end Alembic commands ###
