"""empty message

Revision ID: b03b7beb64cb
Revises: e0c4af92a3da
Create Date: 2021-02-27 03:48:09.321624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b03b7beb64cb'
down_revision = 'e0c4af92a3da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('name', sa.String(length=80), nullable=False))
    op.drop_column('favorites', 'label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('label', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('favorites', 'name')
    # ### end Alembic commands ###
