"""empty message

Revision ID: e0c4af92a3da
Revises: 95ac11e140fd
Create Date: 2021-02-26 23:31:26.186664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0c4af92a3da'
down_revision = '95ac11e140fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('object_id', sa.Integer(), nullable=False))
    op.add_column('favorites', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'user', ['user_id'], ['id'])
    op.drop_column('favorites', 'done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('done', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'user_id')
    op.drop_column('favorites', 'object_id')
    # ### end Alembic commands ###
