"""empty message

Revision ID: ee86092e3711
Revises: 24196c6e3586
Create Date: 2021-02-26 21:22:39.644490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee86092e3711'
down_revision = '24196c6e3586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('birth_year', sa.String(length=80), nullable=False))
    op.add_column('characters', sa.Column('eye_color', sa.String(length=80), nullable=False))
    op.add_column('characters', sa.Column('gender', sa.String(length=80), nullable=False))
    op.add_column('characters', sa.Column('hair_color', sa.String(length=80), nullable=False))
    op.add_column('characters', sa.Column('height', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('homeworld', sa.String(length=80), nullable=False))
    op.add_column('characters', sa.Column('mass', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('name', sa.String(length=80), nullable=False))
    op.add_column('characters', sa.Column('skin_color', sa.String(length=80), nullable=False))
    op.add_column('characters', sa.Column('url', sa.String(length=80), nullable=False))
    op.drop_column('characters', 'label')
    op.drop_column('characters', 'done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('done', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('label', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('characters', 'url')
    op.drop_column('characters', 'skin_color')
    op.drop_column('characters', 'name')
    op.drop_column('characters', 'mass')
    op.drop_column('characters', 'homeworld')
    op.drop_column('characters', 'height')
    op.drop_column('characters', 'hair_color')
    op.drop_column('characters', 'gender')
    op.drop_column('characters', 'eye_color')
    op.drop_column('characters', 'birth_year')
    # ### end Alembic commands ###
